version: '2'
services:
  debian_github_user:
    build: ./
    container_name: github_user
    restart: always
    networks:
      - docker-localhost
    ports:
      - 80:80
networks:
  docker-localhost: