version: '2'
services:
  gfechio_developer:
    build: ./   
    container_name: gfechio_developer
    networks:
      - docker-localhost
    volumes:
      - ../:/var/www/html
    ports:
      - 80:80
      - 22:22
    tty: true
networks:
  docker-localhost: