version: '2'
services:
  github_user:
    build: ./   
    container_name: github_user
    networks:
      - docker-localhost
    volumes:
      - ~/Desktop/GitHubUsers:/var/www/html/GitHubUsers
    ports:
      - 80:80
      - 22:22
    tty: true
networks:
  docker-localhost: